---
- hosts: 10.0.0.206
  tasks:
  - name: Install Telegraf
    apt:
      deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.4.3-1_amd64.deb
  - name: Start Telegraf
    service:
      name: telegraf
      state: started
  - name: configuring Telegraf
    lineinfile:
      path: /etc/selinux/config
      regexp: '^urls = '
      line: 'urls = ["http://localhost:8086"]'
