- name: Install prometheus node-exporter
  hosts: all
  tasks:    
    - name: Add repository
      apt_repository:
        repo: deb http://deb.robustperception.io/ precise nightly
        state: present
    - name: Install prometheus node-exporter using apt
      apt: name={{item}} state=present update_cache=yes allow_unauthenticated=yes
      with_items:
        - prometheus 
        - node-exporter
