---
- hosts: "{{ hosts | mandatory }}"
  become: true
  tasks:
  - name: Install Golang
    apt:
      name: golang-go
      state: present
- hosts: "{{ hosts | mandatory }}"
  become: true
  roles:
    - SoInteractive.nginx
    - tersmitten.fail2ban
- hosts: "{{ hosts | mandatory }}"
  become: true
  roles:
    - tersmitten.fail2ban
