- name: install TICK
  hosts: 10.0.0.206
  remote_user: narwal
  tasks:    
    - name: install docker-py
      pip:
        name: docker-py
    - name: Install TICK role
        roles:
            - mlabouardy.tick
