- name: install TICK
  hosts: 10.0.0.206
  tasks:    
    - name: install docker-py
      pip:
        name: docker-py
    - name: Install prometheus node-exporter using apt
        remote_user: narwal
        roles:
            - mlabouardy.tick
