- name: install install docker-py
  hosts: 10.0.0.206
    tasks:    
    - name: install docker-py using pip
      pip:
        name: docker-py
- hosts: 10.0.0.206
  remote_user: narwal
  roles:
    - mlabouardy.tick
